# Generated by Django 6.0.6 on 2026-08-10 12:30

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], max_length=20)),
                ('object_id', models.IntegerField()),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='llm_searchi_content_e95582_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='search_embedding_hnsw_idx', opclasses=['vector_cosine_ops'])],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]