# Generated by Django 6.0.6 on 2026-08-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_cashed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_image',
            field=models.ImageField(null=True, upload_to='posters/movies/'),
        ),
    ]
