# Generated by Django 6.0.6 on 2026-08-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_movie_is_cashed_alter_movie_poster_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
