name: Build go-streamer binary

on:
    push:
        paths:
            - "go-backend/**"
    workflow_dispatch: {}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v5
              with:
                  go-version: "1.22"
                  cache: true
                  cache-dependency-path: go-backend/go.sum

            - name: Build (linux/amd64)
              working-directory: ./go-backend
              run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o streamer main.go

            - uses: actions/upload-artifact@v4
              with:
                  name: streamer-binary
                  path: go-backend/streamer
