name: Django CD

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: AWS EC2 ga SSH orqali ulanish
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST_DNS }}
                  username: ec2-user
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd /home/ec2-user/video-streaming-plarform
                      git fetch origin main
                      sudo chown -R ec2-user:ec2-user .
                      git reset --hard origin/main

                      if git diff HEAD~1 HEAD --name-only | grep -qE "requirements.txt|Dockerfile|docker-compose.yml|admin-panel/"; then
                        docker-compose build django django2 django3 celery
                        docker-compose run --rm django python manage.py migrate
                        docker-compose run --rm django python manage.py collectstatic --noinput
                        docker-compose up -d --no-deps --force-recreate django
                        sleep 5
                        docker-compose up -d --no-deps --force-recreate django2
                        sleep 5
                        docker-compose up -d --no-deps --force-recreate celery
                      else
                        docker-compose run --rm django python manage.py migrate
                        docker-compose run --rm django python manage.py collectstatic --noinput
                        docker-compose up -d --no-deps --force-recreate django
                        sleep 5
                        docker-compose up -d --no-deps --force-recreate django2
                        sleep 5
                      fi

                      docker image prune -f